/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1AdminCnaesCodigo200,
  ModelsCNAE,
  ModelsCNAEBody,
  ModelsErrorResponse,
} from '.././models'

import { customFetchGoRio } from '../../../custom-fetch-gorio'

/**
 * Cria um novo CNAE (admin)
 * @summary Criar CNAE
 */
export type postApiV1AdminCnaesResponse201 = {
  data: ModelsCNAE
  status: 201
}

export type postApiV1AdminCnaesResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type postApiV1AdminCnaesResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type postApiV1AdminCnaesResponseComposite =
  | postApiV1AdminCnaesResponse201
  | postApiV1AdminCnaesResponse400
  | postApiV1AdminCnaesResponse500

export type postApiV1AdminCnaesResponse =
  postApiV1AdminCnaesResponseComposite & {
    headers: Headers
  }

export const getPostApiV1AdminCnaesUrl = () => {
  return `/api/v1/admin/cnaes`
}

export const postApiV1AdminCnaes = async (
  modelsCNAEBody: ModelsCNAEBody,
  options?: RequestInit
): Promise<postApiV1AdminCnaesResponse> => {
  return customFetchGoRio<postApiV1AdminCnaesResponse>(
    getPostApiV1AdminCnaesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsCNAEBody),
    }
  )
}

/**
 * Atualiza um CNAE existente (admin)
 * @summary Atualizar CNAE
 */
export type putApiV1AdminCnaesCodigoResponse200 = {
  data: ModelsCNAE
  status: 200
}

export type putApiV1AdminCnaesCodigoResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type putApiV1AdminCnaesCodigoResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type putApiV1AdminCnaesCodigoResponseComposite =
  | putApiV1AdminCnaesCodigoResponse200
  | putApiV1AdminCnaesCodigoResponse400
  | putApiV1AdminCnaesCodigoResponse500

export type putApiV1AdminCnaesCodigoResponse =
  putApiV1AdminCnaesCodigoResponseComposite & {
    headers: Headers
  }

export const getPutApiV1AdminCnaesCodigoUrl = (codigo: string) => {
  return `/api/v1/admin/cnaes/${codigo}`
}

export const putApiV1AdminCnaesCodigo = async (
  codigo: string,
  modelsCNAEBody: ModelsCNAEBody,
  options?: RequestInit
): Promise<putApiV1AdminCnaesCodigoResponse> => {
  return customFetchGoRio<putApiV1AdminCnaesCodigoResponse>(
    getPutApiV1AdminCnaesCodigoUrl(codigo),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(modelsCNAEBody),
    }
  )
}

/**
 * Remove um CNAE pelo código (admin)
 * @summary Excluir CNAE
 */
export type deleteApiV1AdminCnaesCodigoResponse200 = {
  data: DeleteApiV1AdminCnaesCodigo200
  status: 200
}

export type deleteApiV1AdminCnaesCodigoResponse400 = {
  data: ModelsErrorResponse
  status: 400
}

export type deleteApiV1AdminCnaesCodigoResponse500 = {
  data: ModelsErrorResponse
  status: 500
}

export type deleteApiV1AdminCnaesCodigoResponseComposite =
  | deleteApiV1AdminCnaesCodigoResponse200
  | deleteApiV1AdminCnaesCodigoResponse400
  | deleteApiV1AdminCnaesCodigoResponse500

export type deleteApiV1AdminCnaesCodigoResponse =
  deleteApiV1AdminCnaesCodigoResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1AdminCnaesCodigoUrl = (codigo: string) => {
  return `/api/v1/admin/cnaes/${codigo}`
}

export const deleteApiV1AdminCnaesCodigo = async (
  codigo: string,
  options?: RequestInit
): Promise<deleteApiV1AdminCnaesCodigoResponse> => {
  return customFetchGoRio<deleteApiV1AdminCnaesCodigoResponse>(
    getDeleteApiV1AdminCnaesCodigoUrl(codigo),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
