/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeCurriculoCompleto,
  GetApiV1EmpregabilidadeCurriculoCpf500,
} from '.././models'

import { customFetchGoRio } from '../../../custom-fetch-gorio'

/**
 * Retorna o currículo completo de um usuário
 * @summary Buscar currículo completo
 */
export type getApiV1EmpregabilidadeCurriculoCpfResponse200 = {
  data: EmpregabilidadeCurriculoCompleto
  status: 200
}

export type getApiV1EmpregabilidadeCurriculoCpfResponse500 = {
  data: GetApiV1EmpregabilidadeCurriculoCpf500
  status: 500
}

export type getApiV1EmpregabilidadeCurriculoCpfResponseComposite =
  | getApiV1EmpregabilidadeCurriculoCpfResponse200
  | getApiV1EmpregabilidadeCurriculoCpfResponse500

export type getApiV1EmpregabilidadeCurriculoCpfResponse =
  getApiV1EmpregabilidadeCurriculoCpfResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeCurriculoCpfUrl = (cpf: string) => {
  return `/api/v1/empregabilidade/curriculo/${cpf}`
}

export const getApiV1EmpregabilidadeCurriculoCpf = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeCurriculoCpfResponse> => {
  return customFetchGoRio<getApiV1EmpregabilidadeCurriculoCpfResponse>(
    getGetApiV1EmpregabilidadeCurriculoCpfUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}
