/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  EmpregabilidadeBancoCurriculoDetalhe,
  EmpregabilidadeBancoCurriculoListResponse,
  GetApiV1EmpregabilidadeBancoCurriculos403,
  GetApiV1EmpregabilidadeBancoCurriculos500,
  GetApiV1EmpregabilidadeBancoCurriculosCpf400,
  GetApiV1EmpregabilidadeBancoCurriculosCpf403,
  GetApiV1EmpregabilidadeBancoCurriculosCpf404,
  GetApiV1EmpregabilidadeBancoCurriculosCpf500,
  GetApiV1EmpregabilidadeBancoCurriculosParams,
} from '../models'

import { customFetchGoRio } from '../../../custom-fetch-gorio'

export type getApiV1EmpregabilidadeBancoCurriculosResponse200 = {
  data: EmpregabilidadeBancoCurriculoListResponse
  status: 200
}

export type getApiV1EmpregabilidadeBancoCurriculosResponse403 = {
  data: GetApiV1EmpregabilidadeBancoCurriculos403
  status: 403
}

export type getApiV1EmpregabilidadeBancoCurriculosResponse500 = {
  data: GetApiV1EmpregabilidadeBancoCurriculos500
  status: 500
}

export type getApiV1EmpregabilidadeBancoCurriculosResponseSuccess =
  getApiV1EmpregabilidadeBancoCurriculosResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeBancoCurriculosResponseError = (
  | getApiV1EmpregabilidadeBancoCurriculosResponse403
  | getApiV1EmpregabilidadeBancoCurriculosResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeBancoCurriculosResponse =
  | getApiV1EmpregabilidadeBancoCurriculosResponseSuccess
  | getApiV1EmpregabilidadeBancoCurriculosResponseError

export const getGetApiV1EmpregabilidadeBancoCurriculosUrl = (
  params?: GetApiV1EmpregabilidadeBancoCurriculosParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/empregabilidade/banco-curriculos?${stringifiedParams}`
    : `/api/v1/empregabilidade/banco-curriculos`
}

/**
 * Lista todos os currículos da base, do mais recente para o mais antigo. Exige admin ou role go:curriculos:admin / go:curriculos:editor.
 * @summary Listar banco de currículos
 */
export const getApiV1EmpregabilidadeBancoCurriculos = async (
  params?: GetApiV1EmpregabilidadeBancoCurriculosParams,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeBancoCurriculosResponse> => {
  return customFetchGoRio<getApiV1EmpregabilidadeBancoCurriculosResponse>(
    getGetApiV1EmpregabilidadeBancoCurriculosUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse200 = {
  data: EmpregabilidadeBancoCurriculoDetalhe
  status: 200
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse400 = {
  data: GetApiV1EmpregabilidadeBancoCurriculosCpf400
  status: 400
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse403 = {
  data: GetApiV1EmpregabilidadeBancoCurriculosCpf403
  status: 403
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse404 = {
  data: GetApiV1EmpregabilidadeBancoCurriculosCpf404
  status: 404
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse500 = {
  data: GetApiV1EmpregabilidadeBancoCurriculosCpf500
  status: 500
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponseSuccess =
  getApiV1EmpregabilidadeBancoCurriculosCpfResponse200 & {
    headers: Headers
  }
export type getApiV1EmpregabilidadeBancoCurriculosCpfResponseError = (
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponse400
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponse403
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponse404
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponse500
) & {
  headers: Headers
}

export type getApiV1EmpregabilidadeBancoCurriculosCpfResponse =
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponseSuccess
  | getApiV1EmpregabilidadeBancoCurriculosCpfResponseError

export const getGetApiV1EmpregabilidadeBancoCurriculosCpfUrl = (
  cpf: string
) => {
  return `/api/v1/empregabilidade/banco-curriculos/${cpf}`
}

/**
 * Retorna a ficha de um currículo: dados pessoais do cadastro do cidadão e o currículo completo. Exige admin ou role go:curriculos:admin / go:curriculos:editor.
 * @summary Detalhar currículo do banco
 */
export const getApiV1EmpregabilidadeBancoCurriculosCpf = async (
  cpf: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeBancoCurriculosCpfResponse> => {
  return customFetchGoRio<getApiV1EmpregabilidadeBancoCurriculosCpfResponse>(
    getGetApiV1EmpregabilidadeBancoCurriculosCpfUrl(cpf),
    {
      ...options,
      method: 'GET',
    }
  )
}
