import type { MappingDetailResponseCreatedBy } from './mappingDetailResponseCreatedBy'
/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Heimdall Admin Service
 * # Heimdall Admin Service API

A comprehensive admin service for user and group management with authorization powered by Cerbos.

## Features

- **User Management**: Automatic user creation from JWT tokens with role-based access control
- **Group Management**: Create, manage, and assign users to groups with hierarchical permissions
- **Role Management**: Define and assign roles to users and groups
- **Mapping Management**: Configure API endpoint to action mappings for authorization
- **Action Management**: Define available actions for fine-grained permission control
- **Cerbos Integration**: Policy-based authorization with external Cerbos service
- **Audit Logging**: Comprehensive audit trail for all administrative operations
- **Redis Caching**: High-performance caching for frequently accessed data
 * OpenAPI spec version: 1.0.0
 */
import type { MappingDetailResponseDescription } from './mappingDetailResponseDescription'
import type { MappingDetailResponseUpdatedAt } from './mappingDetailResponseUpdatedAt'

/**
 * Detailed response model for mapping information.
 */
export interface MappingDetailResponse {
  /** Unique identifier of the mapping */
  id: number
  /** URL path pattern */
  path_pattern: string
  /** HTTP method */
  method: string
  /** Action name */
  action: string
  /** Mapping description */
  description?: MappingDetailResponseDescription
  /** CPF of the user who created this mapping */
  created_by?: MappingDetailResponseCreatedBy
  /** ISO timestamp when the mapping was created */
  created_at: string
  /** ISO timestamp when the mapping was last updated */
  updated_at?: MappingDetailResponseUpdatedAt
}
