/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Heimdall Admin Service
 * # Heimdall Admin Service API

A comprehensive admin service for user and group management with authorization powered by Cerbos.

## Features

- **User Management**: Automatic user creation from JWT tokens with role-based access control
- **Group Management**: Create, manage, and assign users to groups with hierarchical permissions
- **Role Management**: Define and assign roles to users and groups
- **Mapping Management**: Configure API endpoint to action mappings for authorization
- **Action Management**: Define available actions for fine-grained permission control
- **Cerbos Integration**: Policy-based authorization with external Cerbos service
- **Audit Logging**: Comprehensive audit trail for all administrative operations
- **Redis Caching**: High-performance caching for frequently accessed data
 * OpenAPI spec version: 1.0.0
 */
import type { RoleResponse } from './roleResponse'

export interface PaginatedResponseRoleResponse {
  /** List of items for the current page */
  items: RoleResponse[]
  /**
   * Total number of items available
   * @minimum 0
   */
  total: number
  /**
   * Number of items skipped (offset)
   * @minimum 0
   */
  skip: number
  /**
   * Maximum number of items returned
   * @minimum 1
   * @maximum 100
   */
  limit: number
  /** Whether there are more items available */
  has_more: boolean
}
