import type { RoleResponseCreatedAt } from './roleResponseCreatedAt'
/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Heimdall Admin Service
 * # Heimdall Admin Service API

A comprehensive admin service for user and group management with authorization powered by Cerbos.

## Features

- **User Management**: Automatic user creation from JWT tokens with role-based access control
- **Group Management**: Create, manage, and assign users to groups with hierarchical permissions
- **Role Management**: Define and assign roles to users and groups
- **Mapping Management**: Configure API endpoint to action mappings for authorization
- **Action Management**: Define available actions for fine-grained permission control
- **Cerbos Integration**: Policy-based authorization with external Cerbos service
- **Audit Logging**: Comprehensive audit trail for all administrative operations
- **Redis Caching**: High-performance caching for frequently accessed data
 * OpenAPI spec version: 1.0.0
 */
import type { RoleResponseCreatedBy } from './roleResponseCreatedBy'

/**
 * Response model for role information.
 */
export interface RoleResponse {
  /** Unique identifier for the role */
  id: number
  /** Role name */
  name: string
  /** Role description */
  description: string
  /** CPF of the user who created this role (null for system roles) */
  created_by?: RoleResponseCreatedBy
  /** ISO timestamp when the role was created (null for system roles) */
  created_at?: RoleResponseCreatedAt
}
