/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Heimdall Admin Service
 * # Heimdall Admin Service API

A comprehensive admin service for user and group management with authorization powered by Cerbos.

## Features

- **User Management**: Automatic user creation from JWT tokens with role-based access control
- **Group Management**: Create, manage, and assign users to groups with hierarchical permissions
- **Role Management**: Define and assign roles to users and groups
- **Mapping Management**: Configure API endpoint to action mappings for authorization
- **Action Management**: Define available actions for fine-grained permission control
- **Cerbos Integration**: Policy-based authorization with external Cerbos service
- **Audit Logging**: Comprehensive audit trail for all administrative operations
- **Redis Caching**: High-performance caching for frequently accessed data
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDisplayName } from './userResponseDisplayName'

/**
 * Response model for user information.
 */
export interface UserResponse {
  /** Unique identifier for the user */
  id: number
  /**
   * User's CPF (Cadastro de Pessoa Física) - Brazilian tax ID
   * @pattern ^[0-9]{11}$
   */
  cpf: string
  /** User's display name from JWT token (name, given_name, or email) */
  display_name?: UserResponseDisplayName
  /** List of groups the user belongs to */
  groups?: string[]
  /** List of roles assigned to the user (both direct and through groups) */
  roles?: string[]
}
