/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeEmpresa } from './empregabilidadeEmpresa'
import type { EmpregabilidadeEtapa } from './empregabilidadeEtapa'
import type { EmpregabilidadeInformacaoComplementar } from './empregabilidadeInformacaoComplementar'
import type { EmpregabilidadeModeloTrabalho } from './empregabilidadeModeloTrabalho'
import type { EmpregabilidadeRegimeContratacao } from './empregabilidadeRegimeContratacao'
import type { EmpregabilidadeStatusVaga } from './empregabilidadeStatusVaga'
import type { EmpregabilidadeTipoPCD } from './empregabilidadeTipoPCD'

export interface EmpregabilidadeVaga {
  bairro?: string
  beneficios?: string
  /** Relationships */
  contratante?: EmpregabilidadeEmpresa
  created_at?: string
  data_limite?: string
  deleted_at?: string
  descricao?: string
  diferenciais?: string
  etapas?: EmpregabilidadeEtapa[]
  id?: string
  id_contratante?: string
  id_modelo_trabalho?: string
  id_orgao_parceiro?: string
  id_regime_contratacao?: string
  informacoes_complementares?: EmpregabilidadeInformacaoComplementar[]
  modelo_trabalho?: EmpregabilidadeModeloTrabalho
  regime_contratacao?: EmpregabilidadeRegimeContratacao
  requisitos?: string
  responsabilidades?: string
  status?: EmpregabilidadeStatusVaga
  tipos_pcd?: EmpregabilidadeTipoPCD[]
  titulo?: string
  updated_at?: string
  vaga_pcd?: boolean
  valor_vaga?: number
}
