/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeCurriculoCompleto } from './empregabilidadeCurriculoCompleto'

export interface EmpregabilidadeBancoCurriculoDetalhe {
  bairro?: string
  celular?: string
  cpf?: string
  curriculo?: EmpregabilidadeCurriculoCompleto
  /**
   * DataAtualizacao é o último salvamento do currículo pelo cidadão. É nula
   * quando nenhuma seção foi preenchida.
   */
  data_atualizacao?: string
  data_inclusao?: string
  /** Deficiencia é o que o cidadão declarou sobre deficiência (PCD). */
  deficiencia?: string
  email?: string
  escolaridade?: string
  /**
   * Genero é a identidade de gênero autodeclarada. O sexo da base cadastral
   * não é usado como fallback.
   */
  genero?: string
  idade?: number
  nome?: string
  nome_social?: string
  profissao?: string
  raca?: string
}
