/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { EmpregabilidadeBancoCurriculoItem } from './empregabilidadeBancoCurriculoItem'
import type { EmpregabilidadeBancoCurriculoListMeta } from './empregabilidadeBancoCurriculoListMeta'

export interface EmpregabilidadeBancoCurriculoListResponse {
  data?: EmpregabilidadeBancoCurriculoItem[]
  meta?: EmpregabilidadeBancoCurriculoListMeta
}
