/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type GetApiV1CnaesParams = {
  /**
   * Número da página (default: 1)
   */
  page?: number
  /**
   * Tamanho da página (default: 100, max: 1000)
   */
  pageSize?: number
  /**
   * Filtrar por ocupação
   */
  ocupacao?: string
}
