/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsFormaPagamento =
  (typeof ModelsFormaPagamento)[keyof typeof ModelsFormaPagamento]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsFormaPagamento = {
  FormaPagamentoCheque: 'CHEQUE',
  FormaPagamentoDinheiro: 'DINHEIRO',
  FormaPagamentoCartao: 'CARTAO',
  FormaPagamentoTransferencia: 'TRANSFERENCIA',
} as const
