/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */

export type ModelsSituacaoCadastral =
  (typeof ModelsSituacaoCadastral)[keyof typeof ModelsSituacaoCadastral]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsSituacaoCadastral = {
  SituacaoAtiva: 'ATIVA',
  SituacaoSuspensa: 'SUSPENSA',
  SituacaoInapta: 'INAPTA',
  SituacaoBaixada: 'BAIXADA',
  SituacaoNula: 'NULA',
} as const
