/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsCNAE } from './modelsCNAE'
import type { ModelsSituacaoCadastral } from './modelsSituacaoCadastral'

export interface ModelsMEIEmpresa {
  bairro?: string
  /** Endereço */
  cep?: string
  cidade?: string
  cnpj?: string
  created_at?: string
  /** Dados de contato */
  email?: string
  estado?: string
  id?: number
  logradouro?: string
  natureza_juridica?: string
  nome_fantasia?: string
  numero?: string
  porte?: string
  razao_social?: string
  /** Relacionamentos */
  servicos?: ModelsCNAE[]
  situacao_cadastral?: ModelsSituacaoCadastral
  tipo?: string
  updated_at?: string
  whatsapp?: string
}
