/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type { ModelsCurso } from './modelsCurso'
import type { ModelsEmprego } from './modelsEmprego'

export interface ModelsOrgao {
  /** Relacionamentos */
  cursos?: ModelsCurso[]
  empregos?: ModelsEmprego[]
  id?: number
  nome?: string
}
