/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API RMI
 * API para gerenciamento de dados de cidadãos do Rio de Janeiro, incluindo autodeclaração de informações e verificação de contato.
 * OpenAPI spec version: 1.0
 */
import type {
  HandlersErrorResponse,
  HandlersMemoryModel,
  HandlersSuccessResponse,
} from '.././models'

import { customFetchRmi } from '../../../custom-fetch-rmi'

/**
 * Recupera a lista de memórias associadas ao telefone do cidadão.
 * @summary Obter memórias associadas ao número de telefone.
 */
export type getMemoryPhoneNumberResponse200 = {
  data: HandlersMemoryModel[]
  status: 200
}

export type getMemoryPhoneNumberResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getMemoryPhoneNumberResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getMemoryPhoneNumberResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getMemoryPhoneNumberResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type getMemoryPhoneNumberResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMemoryPhoneNumberResponseComposite =
  | getMemoryPhoneNumberResponse200
  | getMemoryPhoneNumberResponse400
  | getMemoryPhoneNumberResponse401
  | getMemoryPhoneNumberResponse403
  | getMemoryPhoneNumberResponse429
  | getMemoryPhoneNumberResponse500

export type getMemoryPhoneNumberResponse =
  getMemoryPhoneNumberResponseComposite & {
    headers: Headers
  }

export const getGetMemoryPhoneNumberUrl = (phoneNumber: string) => {
  return `/memory/${phoneNumber}`
}

export const getMemoryPhoneNumber = async (
  phoneNumber: string,
  options?: RequestInit
): Promise<getMemoryPhoneNumberResponse> => {
  return customFetchRmi<getMemoryPhoneNumberResponse>(
    getGetMemoryPhoneNumberUrl(phoneNumber),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma única memória associada ao telefone do cidadão.
 * @summary Cria memória associada ao número de telefone.
 */
export type postMemoryPhoneNumberResponse201 = {
  data: HandlersMemoryModel
  status: 201
}

export type postMemoryPhoneNumberResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type postMemoryPhoneNumberResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type postMemoryPhoneNumberResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type postMemoryPhoneNumberResponse409 = {
  data: HandlersErrorResponse
  status: 409
}

export type postMemoryPhoneNumberResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type postMemoryPhoneNumberResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type postMemoryPhoneNumberResponseComposite =
  | postMemoryPhoneNumberResponse201
  | postMemoryPhoneNumberResponse400
  | postMemoryPhoneNumberResponse401
  | postMemoryPhoneNumberResponse403
  | postMemoryPhoneNumberResponse409
  | postMemoryPhoneNumberResponse429
  | postMemoryPhoneNumberResponse500

export type postMemoryPhoneNumberResponse =
  postMemoryPhoneNumberResponseComposite & {
    headers: Headers
  }

export const getPostMemoryPhoneNumberUrl = (phoneNumber: string) => {
  return `/memory/${phoneNumber}`
}

export const postMemoryPhoneNumber = async (
  phoneNumber: string,
  handlersMemoryModel: HandlersMemoryModel,
  options?: RequestInit
): Promise<postMemoryPhoneNumberResponse> => {
  return customFetchRmi<postMemoryPhoneNumberResponse>(
    getPostMemoryPhoneNumberUrl(phoneNumber),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(handlersMemoryModel),
    }
  )
}

/**
 * Recupera uma única memória associada ao telefone do cidadão.
 * @summary Obter memória associada ao número de telefone pelo nome.
 */
export type getMemoryPhoneNumberMemoryNameResponse200 = {
  data: HandlersMemoryModel
  status: 200
}

export type getMemoryPhoneNumberMemoryNameResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type getMemoryPhoneNumberMemoryNameResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type getMemoryPhoneNumberMemoryNameResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type getMemoryPhoneNumberMemoryNameResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type getMemoryPhoneNumberMemoryNameResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type getMemoryPhoneNumberMemoryNameResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type getMemoryPhoneNumberMemoryNameResponseComposite =
  | getMemoryPhoneNumberMemoryNameResponse200
  | getMemoryPhoneNumberMemoryNameResponse400
  | getMemoryPhoneNumberMemoryNameResponse401
  | getMemoryPhoneNumberMemoryNameResponse403
  | getMemoryPhoneNumberMemoryNameResponse404
  | getMemoryPhoneNumberMemoryNameResponse429
  | getMemoryPhoneNumberMemoryNameResponse500

export type getMemoryPhoneNumberMemoryNameResponse =
  getMemoryPhoneNumberMemoryNameResponseComposite & {
    headers: Headers
  }

export const getGetMemoryPhoneNumberMemoryNameUrl = (
  phoneNumber: string,
  memoryName: string
) => {
  return `/memory/${phoneNumber}/${memoryName}`
}

export const getMemoryPhoneNumberMemoryName = async (
  phoneNumber: string,
  memoryName: string,
  options?: RequestInit
): Promise<getMemoryPhoneNumberMemoryNameResponse> => {
  return customFetchRmi<getMemoryPhoneNumberMemoryNameResponse>(
    getGetMemoryPhoneNumberMemoryNameUrl(phoneNumber, memoryName),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma única memória associada ao telefone do cidadão.
 * @summary Atualiza memória associada ao número de telefone.
 */
export type putMemoryPhoneNumberMemoryNameResponse200 = {
  data: HandlersSuccessResponse
  status: 200
}

export type putMemoryPhoneNumberMemoryNameResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type putMemoryPhoneNumberMemoryNameResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type putMemoryPhoneNumberMemoryNameResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type putMemoryPhoneNumberMemoryNameResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type putMemoryPhoneNumberMemoryNameResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type putMemoryPhoneNumberMemoryNameResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type putMemoryPhoneNumberMemoryNameResponseComposite =
  | putMemoryPhoneNumberMemoryNameResponse200
  | putMemoryPhoneNumberMemoryNameResponse400
  | putMemoryPhoneNumberMemoryNameResponse401
  | putMemoryPhoneNumberMemoryNameResponse403
  | putMemoryPhoneNumberMemoryNameResponse404
  | putMemoryPhoneNumberMemoryNameResponse429
  | putMemoryPhoneNumberMemoryNameResponse500

export type putMemoryPhoneNumberMemoryNameResponse =
  putMemoryPhoneNumberMemoryNameResponseComposite & {
    headers: Headers
  }

export const getPutMemoryPhoneNumberMemoryNameUrl = (
  phoneNumber: string,
  memoryName: string
) => {
  return `/memory/${phoneNumber}/${memoryName}`
}

export const putMemoryPhoneNumberMemoryName = async (
  phoneNumber: string,
  memoryName: string,
  handlersMemoryModel: HandlersMemoryModel,
  options?: RequestInit
): Promise<putMemoryPhoneNumberMemoryNameResponse> => {
  return customFetchRmi<putMemoryPhoneNumberMemoryNameResponse>(
    getPutMemoryPhoneNumberMemoryNameUrl(phoneNumber, memoryName),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(handlersMemoryModel),
    }
  )
}

/**
 * Deleta uma única memória associada ao telefone do cidadão.
 * @summary Deleta memória associada ao número de telefone.
 */
export type deleteMemoryPhoneNumberMemoryNameResponse204 = {
  data: null
  status: 204
}

export type deleteMemoryPhoneNumberMemoryNameResponse400 = {
  data: HandlersErrorResponse
  status: 400
}

export type deleteMemoryPhoneNumberMemoryNameResponse401 = {
  data: HandlersErrorResponse
  status: 401
}

export type deleteMemoryPhoneNumberMemoryNameResponse403 = {
  data: HandlersErrorResponse
  status: 403
}

export type deleteMemoryPhoneNumberMemoryNameResponse404 = {
  data: HandlersErrorResponse
  status: 404
}

export type deleteMemoryPhoneNumberMemoryNameResponse429 = {
  data: HandlersErrorResponse
  status: 429
}

export type deleteMemoryPhoneNumberMemoryNameResponse500 = {
  data: HandlersErrorResponse
  status: 500
}

export type deleteMemoryPhoneNumberMemoryNameResponseComposite =
  | deleteMemoryPhoneNumberMemoryNameResponse204
  | deleteMemoryPhoneNumberMemoryNameResponse400
  | deleteMemoryPhoneNumberMemoryNameResponse401
  | deleteMemoryPhoneNumberMemoryNameResponse403
  | deleteMemoryPhoneNumberMemoryNameResponse404
  | deleteMemoryPhoneNumberMemoryNameResponse429
  | deleteMemoryPhoneNumberMemoryNameResponse500

export type deleteMemoryPhoneNumberMemoryNameResponse =
  deleteMemoryPhoneNumberMemoryNameResponseComposite & {
    headers: Headers
  }

export const getDeleteMemoryPhoneNumberMemoryNameUrl = (
  phoneNumber: string,
  memoryName: string
) => {
  return `/memory/${phoneNumber}/${memoryName}`
}

export const deleteMemoryPhoneNumberMemoryName = async (
  phoneNumber: string,
  memoryName: string,
  options?: RequestInit
): Promise<deleteMemoryPhoneNumberMemoryNameResponse> => {
  return customFetchRmi<deleteMemoryPhoneNumberMemoryNameResponse>(
    getDeleteMemoryPhoneNumberMemoryNameUrl(phoneNumber, memoryName),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
