/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Go
 * API de serviços para aplicativos da Prefeitura do Rio
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId200,
  DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId400,
  DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId500,
  EmpregabilidadeEtapa,
  EmpregabilidadeEtapaBody,
  GetApiV1EmpregabilidadeVagasVagaIdEtapas200,
  GetApiV1EmpregabilidadeVagasVagaIdEtapas400,
  GetApiV1EmpregabilidadeVagasVagaIdEtapas500,
  GetApiV1EmpregabilidadeVagasVagaIdEtapasId400,
  GetApiV1EmpregabilidadeVagasVagaIdEtapasId404,
  GetApiV1EmpregabilidadeVagasVagaIdEtapasId500,
  PostApiV1EmpregabilidadeVagasVagaIdEtapas400,
  PostApiV1EmpregabilidadeVagasVagaIdEtapas500,
  PutApiV1EmpregabilidadeVagasVagaIdEtapasId400,
  PutApiV1EmpregabilidadeVagasVagaIdEtapasId500,
} from '.././models'

import { customFetchGoRio } from '../../../custom-fetch-gorio'

/**
 * Retorna todas as etapas de uma vaga
 * @summary Listar etapas da vaga
 */
export type getApiV1EmpregabilidadeVagasVagaIdEtapasResponse200 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapas200
  status: 200
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasResponse400 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapas400
  status: 400
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasResponse500 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapas500
  status: 500
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasResponseComposite =
  | getApiV1EmpregabilidadeVagasVagaIdEtapasResponse200
  | getApiV1EmpregabilidadeVagasVagaIdEtapasResponse400
  | getApiV1EmpregabilidadeVagasVagaIdEtapasResponse500

export type getApiV1EmpregabilidadeVagasVagaIdEtapasResponse =
  getApiV1EmpregabilidadeVagasVagaIdEtapasResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeVagasVagaIdEtapasUrl = (
  vagaId: string
) => {
  return `/api/v1/empregabilidade/vagas/${vagaId}/etapas`
}

export const getApiV1EmpregabilidadeVagasVagaIdEtapas = async (
  vagaId: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasVagaIdEtapasResponse> => {
  return customFetchGoRio<getApiV1EmpregabilidadeVagasVagaIdEtapasResponse>(
    getGetApiV1EmpregabilidadeVagasVagaIdEtapasUrl(vagaId),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Cria uma nova etapa para uma vaga
 * @summary Criar etapa
 */
export type postApiV1EmpregabilidadeVagasVagaIdEtapasResponse201 = {
  data: EmpregabilidadeEtapa
  status: 201
}

export type postApiV1EmpregabilidadeVagasVagaIdEtapasResponse400 = {
  data: PostApiV1EmpregabilidadeVagasVagaIdEtapas400
  status: 400
}

export type postApiV1EmpregabilidadeVagasVagaIdEtapasResponse500 = {
  data: PostApiV1EmpregabilidadeVagasVagaIdEtapas500
  status: 500
}

export type postApiV1EmpregabilidadeVagasVagaIdEtapasResponseComposite =
  | postApiV1EmpregabilidadeVagasVagaIdEtapasResponse201
  | postApiV1EmpregabilidadeVagasVagaIdEtapasResponse400
  | postApiV1EmpregabilidadeVagasVagaIdEtapasResponse500

export type postApiV1EmpregabilidadeVagasVagaIdEtapasResponse =
  postApiV1EmpregabilidadeVagasVagaIdEtapasResponseComposite & {
    headers: Headers
  }

export const getPostApiV1EmpregabilidadeVagasVagaIdEtapasUrl = (
  vagaId: string
) => {
  return `/api/v1/empregabilidade/vagas/${vagaId}/etapas`
}

export const postApiV1EmpregabilidadeVagasVagaIdEtapas = async (
  vagaId: string,
  empregabilidadeEtapaBody: EmpregabilidadeEtapaBody,
  options?: RequestInit
): Promise<postApiV1EmpregabilidadeVagasVagaIdEtapasResponse> => {
  return customFetchGoRio<postApiV1EmpregabilidadeVagasVagaIdEtapasResponse>(
    getPostApiV1EmpregabilidadeVagasVagaIdEtapasUrl(vagaId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEtapaBody),
    }
  )
}

/**
 * Retorna uma etapa pelo ID
 * @summary Buscar etapa
 */
export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200 = {
  data: EmpregabilidadeEtapa
  status: 200
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapasId400
  status: 400
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse404 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapasId404
  status: 404
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500 = {
  data: GetApiV1EmpregabilidadeVagasVagaIdEtapasId500
  status: 500
}

export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite =
  | getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200
  | getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400
  | getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse404
  | getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500

export type getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse =
  getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite & {
    headers: Headers
  }

export const getGetApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl = (
  vagaId: string,
  id: string
) => {
  return `/api/v1/empregabilidade/vagas/${vagaId}/etapas/${id}`
}

export const getApiV1EmpregabilidadeVagasVagaIdEtapasId = async (
  vagaId: string,
  id: string,
  options?: RequestInit
): Promise<getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse> => {
  return customFetchGoRio<getApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse>(
    getGetApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl(vagaId, id),
    {
      ...options,
      method: 'GET',
    }
  )
}

/**
 * Atualiza uma etapa existente
 * @summary Atualizar etapa
 */
export type putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200 = {
  data: EmpregabilidadeEtapa
  status: 200
}

export type putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400 = {
  data: PutApiV1EmpregabilidadeVagasVagaIdEtapasId400
  status: 400
}

export type putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500 = {
  data: PutApiV1EmpregabilidadeVagasVagaIdEtapasId500
  status: 500
}

export type putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite =
  | putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200
  | putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400
  | putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500

export type putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse =
  putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite & {
    headers: Headers
  }

export const getPutApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl = (
  vagaId: string,
  id: string
) => {
  return `/api/v1/empregabilidade/vagas/${vagaId}/etapas/${id}`
}

export const putApiV1EmpregabilidadeVagasVagaIdEtapasId = async (
  vagaId: string,
  id: string,
  empregabilidadeEtapaBody: EmpregabilidadeEtapaBody,
  options?: RequestInit
): Promise<putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse> => {
  return customFetchGoRio<putApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse>(
    getPutApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl(vagaId, id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(empregabilidadeEtapaBody),
    }
  )
}

/**
 * Remove uma etapa pelo ID
 * @summary Excluir etapa
 */
export type deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200 = {
  data: DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId200
  status: 200
}

export type deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400 = {
  data: DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId400
  status: 400
}

export type deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500 = {
  data: DeleteApiV1EmpregabilidadeVagasVagaIdEtapasId500
  status: 500
}

export type deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite =
  | deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse200
  | deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse400
  | deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse500

export type deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse =
  deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponseComposite & {
    headers: Headers
  }

export const getDeleteApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl = (
  vagaId: string,
  id: string
) => {
  return `/api/v1/empregabilidade/vagas/${vagaId}/etapas/${id}`
}

export const deleteApiV1EmpregabilidadeVagasVagaIdEtapasId = async (
  vagaId: string,
  id: string,
  options?: RequestInit
): Promise<deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse> => {
  return customFetchGoRio<deleteApiV1EmpregabilidadeVagasVagaIdEtapasIdResponse>(
    getDeleteApiV1EmpregabilidadeVagasVagaIdEtapasIdUrl(vagaId, id),
    {
      ...options,
      method: 'DELETE',
    }
  )
}
