/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AdminServicesParams = {
  /**
   * Página
   */
  page?: number
  /**
   * Resultados por página
   */
  per_page?: number
  /**
   * Status do serviço (0=Draft, 1=Published)
   */
  status?: number
  /**
   * Filtrar por autor
   */
  author?: string
  /**
   * Filtrar por tema geral
   */
  tema_geral?: string
  /**
   * Filtrar por aguardando aprovação
   */
  awaiting_approval?: boolean
  /**
   * Campo para filtro dinâmico
   */
  field?: string
  /**
   * Valor para filtro dinâmico (usado com field)
   */
  value?: string
}
