/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GetApiV1BuscaHibridaMultiParams = {
  /**
   * Lista de colecoes separadas por virgula
   */
  collections: string
  /**
   * Termo de busca
   */
  q: string
  /**
   * Pagina
   */
  page?: number
  /**
   * Resultados por pagina
   */
  per_page?: number
}
