/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */

export type GithubComPrefeituraRioAppBuscaSearchInternalModelsTombamentoRequestOrigem =
  (typeof GithubComPrefeituraRioAppBuscaSearchInternalModelsTombamentoRequestOrigem)[keyof typeof GithubComPrefeituraRioAppBuscaSearchInternalModelsTombamentoRequestOrigem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GithubComPrefeituraRioAppBuscaSearchInternalModelsTombamentoRequestOrigem =
  {
    '1746_v2_llm': '1746_v2_llm',
    'carioca-digital_v2_llm': 'carioca-digital_v2_llm',
  } as const
