/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { GithubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersion } from './githubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersion'

export interface GithubComPrefeituraRioAppBuscaSearchInternalModelsVersionHistory {
  found?: number
  out_of?: number
  page?: number
  versions?: GithubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersion[]
}
