/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { GithubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersionChangeType } from './githubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersionChangeType'

export interface GithubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersion {
  autor?: string
  awaiting_approval?: boolean
  canais_digitais?: string[]
  canais_presenciais?: string[]
  change_reason?: string
  change_type: GithubComPrefeituraRioAppBuscaSearchInternalModelsServiceVersionChangeType
  /** Campos de mudança (armazenados como JSON string no Typesense) */
  changed_fields_json?: string
  created_at?: number
  created_by: string
  created_by_cpf: string
  custo_servico?: string
  descricao_completa?: string
  documentos_necessarios?: string[]
  /** Hash do embedding para verificação (não armazenamos o embedding completo) */
  embedding_hash?: string
  fixar_destaque?: boolean
  id?: string
  instrucoes_solicitante?: string
  is_free?: boolean
  is_rollback?: boolean
  legislacao_relacionada?: string[]
  /** Snapshot completo do serviço (sem embedding para economizar espaço) */
  nome_servico?: string
  orgao_gestor?: string[]
  previous_version?: number
  publico_especifico?: string[]
  published_at?: number
  resultado_solicitacao?: string
  resumo?: string
  rollback_to_version?: number
  search_content?: string
  service_id: string
  servico_nao_cobre?: string
  status?: number
  tema_geral?: string
  tempo_atendimento?: string
  version_number: number
}
