/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsAgentsConfig } from './modelsAgentsConfig'
import type { ModelsPrefRioServiceExtraFields } from './modelsPrefRioServiceExtraFields'

export interface ModelsPrefRioService {
  agents?: ModelsAgentsConfig
  autor: string
  awaiting_approval?: boolean
  canais_digitais?: string[]
  canais_presenciais?: string[]
  created_at?: number
  custo_servico: string
  descricao_completa: string
  documentos_necessarios?: string[]
  embedding?: number[]
  extra_fields?: ModelsPrefRioServiceExtraFields
  fixar_destaque?: boolean
  id?: string
  instrucoes_solicitante?: string
  last_update?: number
  legislacao_relacionada?: string[]
  /** @maxLength 255 */
  nome_servico: string
  /** @minItems 1 */
  orgao_gestor: string[]
  publico_especifico?: string[]
  resultado_solicitacao: string
  /** @maxLength 350 */
  resumo: string
  search_content?: string
  servico_nao_cobre?: string
  /**
   * 0=Draft, 1=Published
   * @minimum 0
   * @maximum 1
   */
  status?: number
  tema_geral: string
  tempo_atendimento: string
}
