/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsAgentsConfig } from './modelsAgentsConfig'
import type { ModelsPrefRioServiceRequestExtraFields } from './modelsPrefRioServiceRequestExtraFields'

export interface ModelsPrefRioServiceRequest {
  agents?: ModelsAgentsConfig
  awaiting_approval?: boolean
  canais_digitais?: string[]
  canais_presenciais?: string[]
  custo_servico: string
  descricao_completa: string
  documentos_necessarios?: string[]
  extra_fields?: ModelsPrefRioServiceRequestExtraFields
  fixar_destaque?: boolean
  instrucoes_solicitante?: string
  legislacao_relacionada?: string[]
  /** @maxLength 255 */
  nome_servico: string
  /** @minItems 1 */
  orgao_gestor: string[]
  publico_especifico?: string[]
  resultado_solicitacao: string
  /** @maxLength 350 */
  resumo: string
  servico_nao_cobre?: string
  /**
   * @minimum 0
   * @maximum 1
   */
  status?: number
  tema_geral: string
  tempo_atendimento: string
}
