/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Mecanismo de Busca API
 * API para busca textual e vetorial usando Typesense e embeddings gerados via Google Gemini
 * OpenAPI spec version: 1.0
 */
import type { ModelsTombamentoOrigem } from './modelsTombamentoOrigem'

export interface ModelsTombamento {
  criado_em?: number
  criado_por: string
  id?: string
  id_servico_antigo: string
  id_servico_novo: string
  observacoes?: string
  origem: ModelsTombamentoOrigem
}
